version: '3.3'
services:
  db:
    image: mysql:8.0.31
    restart: 'no'
    environment:
      MYSQL_DATABASE: 'blood_donation'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: